model_name: "microsoft/phi-1.5"
data_dir: "transcript_files/"
train_args:
  output_dir: "ad-phi1.5"
  evaluation_strategy: "epoch"
  learning_rate: 1e-4
  per_device_train_batch_size: 8
  report_to: "wandb"
  do_eval: True
  num_train_epochs: 20.0
  logging_strategy: 'epoch'
  push_to_hub: True
  push_to_hub_model_id: 'ad-phi1.5'
  run_name: 'run4-phi1.5'
